<?php

$servicesList = [
    1 => [
        'typeService' => "Toilettage",
        'nomService' => "Bain",
        'prixPetit' => '28',
        'prixMoyen' => '45',
        'prixGrand' => '50',
        'description' => "Déscription du service proposé",
    ],
    2 => [
        'typeService' => "Toilettage",
        'nomService' => "Tonte",
        'prixPetit' => 45,
        'prixMoyen' => 55,
        'prixGrand' => 65,
        'description' => "Déscription du service proposé",
    ],
    3 => [
        'typeService' => "Toilettage",
        'nomService' => "Coupe ciseaux",
        'prixPetit' => 53,
        'prixMoyen' => 65,
        'prixGrand' => 75,
        'description' => "Déscription du service proposé",
    ],
    4 => [
        'typeService' => "Toilettage",
        'nomService' => "Epilation",
        'prixPetit' => 60,
        'prixMoyen' => 65,
        'prixGrand' => 70,
        'description' => "Déscription du service proposé",
    ],
    5 => [
        'typeService' => "Toilettage",
        'nomService' => "Coupe griffes",
        'prixPetit' => 5,
        'prixMoyen' => 5,
        'prixGrand' => 5,
        'description' => "Déscription du service proposé",
    ],
    6 => [
        'typeService' => "Toilettage",
        'nomService' => "Démélage",
        'prixPetit' => 5,
        'prixMoyen' => 5,
        'prixGrand' => 5,
        'description' => "Déscription du service proposé",
    ],
    7 => [
        'typeService' => "Spa",
        'nomService' => "Massage",
        'prixPetit' => 25,
        'prixMoyen' => 35,
        'prixGrand' => 45,
        'description' => "Déscription du service proposé",
    ],
    8 => [
        'typeService' => "Spa",
        'nomService' => "Traitement des coussinets",
        'prixPetit' => 20,
        'prixMoyen' => 20,
        'prixGrand' => 20,
        'description' => "Déscription du service proposé",
    ],
    9 => [
        'typeService' => "Spa",
        'nomService' => "Bain aromatique",
        'prixPetit' => 38,
        'prixMoyen' => 52,
        'prixGrand' => 62,
        'description' => "Déscription du service proposé",
    ],
    10 => [
        'typeService' => "Spa",
        'nomService' => "Thalassothérapie",
        'prixPetit' => 60,
        'prixMoyen' => 75,
        'prixGrand' => 85,
        'description' => "Déscription du service proposé",
    ],
];